### ISSUE TITLE
update_mongodb very inefficient

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/data-CAT#9]
When creating a `Mongodb` instance using the `Database` class, the `update_mongodb` method is invoke like:
```python
db.update_mongodb({'ligand': df})
```
Where `df` is a *Pandas* Dataframe.

The method first calls `df_to_mongo_dict` and then `_get_unflattend`. This last function consumes an enormous amount of memory and is extremely slow.

Also, There is a for [loop iterating over the items and indices](https://github.com/nlesc-nano/data-CAT/blob/master/dataCAT/database_functions.py#L199) that is quite inefficient.

**Comment by BvB93** [comment]
The first issue is being looked at.

As for the second one: i'm not particulary concerned about its performance inpact, as the function is called rather infrequently and the number of collumns is generally quite small (1 or 2 dozen at most).
